version: '3.8'

services:
  master:
    container_name: master
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command:
      - -f=/mnt/locust/locustfile.py
      # - --headless # run locust without web interface
      - --master
      - -H=http://www.example.com:8080
      - --users=100
      - --spawn-rate=10
      - --run-time=1m

  # docker-compose up --scale worker=4
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command:
      - -f=/mnt/locust/locustfile.py
      - --worker
      - --master-host=master
