version: '3.8'

volumes:
  prometheus-data:
    driver: local
    name: prometheus-data
    labels:
      owner: markruler
      purpose: personal-computer

services:
  # System Metritc 정보를 Exporter로부터 수집해서 시계열 데이터베이스에 저장
  # PromQL을 통해 조회할 수 있는 기능 제공
  # 사용자가 정의한 임계값(Threshold)을 기준으로 경고를 발생시키는 기능 제공
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.42.0
    restart: always
    ports:
      - 9090:9090
    volumes: # host:container
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      # https://manpages.debian.org/unstable/prometheus/prometheus.1.en.html
      - '--config.file=/etc/prometheus/prometheus.yaml'
      # https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.retention.size=10GB'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - node-exporter
      - snmp-exporter
      - blackbox-exporter
  
  # Alert Manager는 Prometheus에서 생성한 경고를 처리하고 알림을 관리하는 도구
  # alertmanager:
  #   image: prom/alertmanager:v0.25.0
  #   container_name: alertmanager
  #   restart: always
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - ./alertmanager/:/etc/alertmanager/
  #   command:
  #     - '--config.file=/etc/alertmanager/config.yml'
  #     - '--storage.path=/alertmanager'
  #   depends_on:
  #     - prometheus

  # Node의 메트릭 정보를 수집하는 Exporter
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.5.0
    restart: always
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      # - --collector.filesystem.ignored-mount-points
      # - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  # Blackbox Exporter는 서비스 및 애플리케이션의 상태를 모니터링하기 위한 Exporter
  # HTTP, HTTPS, DNS, TCP, ICMP 등의 프로토콜을 통해 서비스의 상태를 모니터링할 수 있다.
  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:v0.23.0
    ports:
      - "9115:9115"
    command:
      - '--config.file=/etc/blackbox-exporter/config.yaml'
    volumes:
      - ./blackbox-exporter/config.yaml:/etc/blackbox-exporter/config.yaml

  # https://github.com/prometheus/snmp_exporter
  # https://hub.docker.com/r/prom/snmp-exporter
  snmp-exporter:
    container_name: snmp-exporter
    image: prom/snmp-exporter:v0.24.1
    restart: always
    ports:
      - 9116:9116
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"
