# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: "proxy"
    org_id: 1
    url: http://prometheus:9090
    is_default: true
    version: 1
    editable: true
  # - name: myinfluxdb
  #   type: influxdb
  #   access: proxy
  #   database: k6
  #   orgId: 1
  #   url: http://influxdb:8086
  #   isDefault: true
