apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: myinfluxdb
    orgId: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  - name: myinfluxdb
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    database: k6
    editable: true # database가 없으면 수동으로 수정해야 함
    isDefault: true
